name: SkyWars
main: org.sobadfish.skywars.SkyWarsMain
version: 1.0.0
api:
  - 1.0.11
  - 3.0.0
author: sobadfish&GouDan888
load: POSTWORLD
description: "空岛战争小游戏"

softdepend:
  - ScoreboardPlugin

loadbefore:
  - ScoreboardPlugin
